### ISSUE TITLE
memory.cc consistently failing assertion.

### ISSUE THREAD

**Issue by bryngo** [jlpteaching/ECS154B#18]
In memory.cc, lines 44 - 64

```
// get pointer from map.
    auto it = dataStorage.find(address);
    if (it == dataStorage.end()) {
        uint8_t *new_data = new uint8_t[lineSize];
        memset(new_data, 1, lineSize);
        dataStorage[address] = {new_data, false};
    }

    uint8_t* mem_data = dataStorage[address].data;

    if (data) {

        // Instead of writing the data, make sure the data is correct.
        bool match = compareData(mem_data, data, lineSize);
        if (!match) {
            std::cout << "Address " << std::hex << address << std::endl;
            std::cout << "ERROR! Writeback contains wrong data." << std::endl;
            assert(0); // Assert for easier gdb
        }
        // Now that it's written back, it's no longer dirty in the cache
        dataStorage[address].dirty = false;
    } else {...
```

We allocate new space in the dataStorage container whenever we are trying to write back to a memory address we haven't seen before. We then proceed to set the data of this newly allocated memory address to 0 (8 bytes of it to be exact) in the call to `memset()`.

In the case where we created a newly generated address in `dataStorage`, the next line, `uint8_t * mem_data = dataStorage[address].data`  assigns `mem_data` to an array filled with 1s.

Now, wouldn't the call to `compareData()` always return false (except on coincidence)? Not sure if I'm missing something here.

**Comment by animalvgamer** [comment]
Well this code is to check the value your cache provides against the value the processor tells the memory it should expect earlier, not what the cache says. The check works in a correctly working cache, so you should check if you're passing your data around correctly.

**Comment by bryngo** [comment]
Figured out the problem! 

For documentation purposes, I'll say that I may have been trying to dig a bit too deep into the code. If anyone runs into a similar problem, just make sure you are using the correct write_back address.

I ran into this issue while running a 2-way SA cache with the given example load / store instructions.
