### ISSUE TITLE
Is it possible to allow public access to Lecture Notes?

### ISSUE THREAD

**Issue by itviewer** [jlpteaching/ECS154B#66]
I am not a student of your school and do not have permission to access the [Lecture Notes](https://ucdavis365-my.sharepoint.com/:o:/g/personal/jlowepower_ucdavis_edu/El-DA5B06wNOpS3DzLCLsWYBLw2X5dl4743mokLQqoQsfQ?e=jGOhK1) 
However, I really want to learn DINO CPU based on your Lecture Notes, so is it possible to allow public access to the Lecture Notes?
Thanks.

**Comment by powerjg** [comment]
I'm not sure why that isn't public. I don't remember restricting it to UC Davis only.

However, all of my lectures from Spring 2020 are on line here: https://jlpteaching.github.io/ECS154B/materials/
